from datetime import datetime, timedelta
import random

# Fallback Data to simulate the Databases
# Rich dataset for the circular network graph visualization

MOCK_CASES = [
    {
        "id": "C-2023-0891",
        "fir_number": "FIR/2023/891",
        "category": "Organized Crime",
        "status": "Open",
        "police_station": "Central PS",
        "district": "Mumbai City",
        "state": "Maharashtra",
        "date_registered": "2023-10-12",
        "date_of_occurrence": "2023-10-10",
        "investigating_officer": "Insp. R. Sharma",
        "linked_entity_count": 14,
        "open_lead_count": 3
    },
    {
        "id": "C-2023-0902",
        "fir_number": "FIR/2023/902",
        "category": "Financial Fraud",
        "status": "Under Investigation",
        "police_station": "Cyber Cell",
        "district": "Pune",
        "state": "Maharashtra",
        "date_registered": "2023-11-05",
        "date_of_occurrence": "2023-11-01",
        "investigating_officer": "SI T. Desai",
        "linked_entity_count": 8,
        "open_lead_count": 1
    },
    {
        "id": "C-2024-0015",
        "fir_number": "FIR/2024/015",
        "category": "Narcotics",
        "status": "Open",
        "police_station": "NCB Mumbai",
        "district": "Mumbai Suburban",
        "state": "Maharashtra",
        "date_registered": "2024-01-18",
        "date_of_occurrence": "2024-01-15",
        "investigating_officer": "Insp. M. Kulkarni",
        "linked_entity_count": 22,
        "open_lead_count": 5
    },
    {
        "id": "C-2024-0042",
        "fir_number": "FIR/2024/042",
        "category": "Extortion",
        "status": "Under Investigation",
        "police_station": "Crime Branch",
        "district": "Thane",
        "state": "Maharashtra",
        "date_registered": "2024-02-20",
        "date_of_occurrence": "2024-02-18",
        "investigating_officer": "SI P. Joshi",
        "linked_entity_count": 11,
        "open_lead_count": 2
    },
    {
        "id": "C-2024-0078",
        "fir_number": "FIR/2024/078",
        "category": "Cyber Crime",
        "status": "Open",
        "police_station": "Cyber Cell II",
        "district": "Bangalore Urban",
        "state": "Karnataka",
        "date_registered": "2024-03-10",
        "date_of_occurrence": "2024-03-08",
        "investigating_officer": "Insp. K. Reddy",
        "linked_entity_count": 9,
        "open_lead_count": 4
    },
]

# ---------- NODES ----------

MOCK_NODES = [
    # ── Persons (25) ──
    {"id": "P-001", "label": "Person", "properties": {"name": "Arjun Kumar", "alias": "AK", "phone": "98XXXXXX12", "age": 34, "city": "Mumbai"}},
    {"id": "P-002", "label": "Person", "properties": {"name": "Vikram Singh", "alias": "Vicky", "phone": "99XXXXXX45", "age": 29, "city": "Mumbai"}},
    {"id": "P-003", "label": "Person", "properties": {"name": "Rajesh Patil", "alias": "Raju", "phone": "97XXXXXX33", "age": 42, "city": "Pune"}},
    {"id": "P-004", "label": "Person", "properties": {"name": "Sunil Yadav", "alias": "Sunny", "phone": "98XXXXXX67", "age": 31, "city": "Thane"}},
    {"id": "P-005", "label": "Person", "properties": {"name": "Mohammed Shaikh", "alias": "MS", "phone": "90XXXXXX88", "age": 38, "city": "Mumbai"}},
    {"id": "P-006", "label": "Person", "properties": {"name": "Deepak Jha", "alias": "DJ", "phone": "91XXXXXX22", "age": 27, "city": "Navi Mumbai"}},
    {"id": "P-007", "label": "Person", "properties": {"name": "Priya Sharma", "alias": None, "phone": "99XXXXXX11", "age": 33, "city": "Mumbai"}},
    {"id": "P-008", "label": "Person", "properties": {"name": "Amit Tiwari", "alias": "Ammu", "phone": "98XXXXXX44", "age": 36, "city": "Pune"}},
    {"id": "P-009", "label": "Person", "properties": {"name": "Ravi Deshmukh", "alias": None, "phone": "97XXXXXX55", "age": 45, "city": "Nagpur"}},
    {"id": "P-010", "label": "Person", "properties": {"name": "Kunal Mehta", "alias": "KM", "phone": "90XXXXXX99", "age": 28, "city": "Mumbai"}},
    {"id": "P-011", "label": "Person", "properties": {"name": "Sanjay Gupta", "alias": "Sandy", "phone": "88XXXXXX77", "age": 41, "city": "Delhi"}},
    {"id": "P-012", "label": "Person", "properties": {"name": "Farhan Ali", "alias": "FA", "phone": "99XXXXXX66", "age": 30, "city": "Mumbai"}},
    {"id": "P-013", "label": "Person", "properties": {"name": "Nitin Sawant", "alias": None, "phone": "97XXXXXX88", "age": 35, "city": "Thane"}},
    {"id": "P-014", "label": "Person", "properties": {"name": "Ganesh Patole", "alias": "GP", "phone": "96XXXXXX22", "age": 39, "city": "Pune"}},
    {"id": "P-015", "label": "Person", "properties": {"name": "Rohit Verma", "alias": None, "phone": "95XXXXXX33", "age": 26, "city": "Bangalore"}},
    {"id": "P-016", "label": "Person", "properties": {"name": "Anil Kapoor", "alias": "AK2", "phone": "94XXXXXX44", "age": 50, "city": "Mumbai"}},
    {"id": "P-017", "label": "Person", "properties": {"name": "Manish Teli", "alias": None, "phone": "93XXXXXX55", "age": 32, "city": "Navi Mumbai"}},
    {"id": "P-018", "label": "Person", "properties": {"name": "Yusuf Khan", "alias": "YK", "phone": "92XXXXXX66", "age": 37, "city": "Mumbai"}},
    {"id": "P-019", "label": "Person", "properties": {"name": "Santosh More", "alias": None, "phone": "91XXXXXX77", "age": 44, "city": "Pune"}},
    {"id": "P-020", "label": "Person", "properties": {"name": "Vinod Chauhan", "alias": "VC", "phone": "90XXXXXX11", "age": 33, "city": "Delhi"}},
    {"id": "P-021", "label": "Person", "properties": {"name": "Prakash Bhosle", "alias": None, "phone": "89XXXXXX22", "age": 48, "city": "Mumbai"}},
    {"id": "P-022", "label": "Person", "properties": {"name": "Ajay Shinde", "alias": "AJ", "phone": "88XXXXXX33", "age": 29, "city": "Thane"}},
    {"id": "P-023", "label": "Person", "properties": {"name": "Kiran Jadhav", "alias": None, "phone": "87XXXXXX44", "age": 36, "city": "Pune"}},
    {"id": "P-024", "label": "Person", "properties": {"name": "Sachin Wagh", "alias": "SW", "phone": "86XXXXXX55", "age": 31, "city": "Nagpur"}},
    {"id": "P-025", "label": "Person", "properties": {"name": "Dilip Pawar", "alias": None, "phone": "85XXXXXX66", "age": 43, "city": "Mumbai"}},

    # ── Phones (18) ──
    {"id": "Ph-001", "label": "Phone", "properties": {"number": "98XXXXXX12", "provider": "Jio", "imei": "35XXXX001"}},
    {"id": "Ph-002", "label": "Phone", "properties": {"number": "99XXXXXX45", "provider": "Airtel", "imei": "35XXXX002"}},
    {"id": "Ph-003", "label": "Phone", "properties": {"number": "97XXXXXX33", "provider": "Vi", "imei": "35XXXX003"}},
    {"id": "Ph-004", "label": "Phone", "properties": {"number": "98XXXXXX67", "provider": "Jio", "imei": "35XXXX004"}},
    {"id": "Ph-005", "label": "Phone", "properties": {"number": "90XXXXXX88", "provider": "BSNL", "imei": "35XXXX005"}},
    {"id": "Ph-006", "label": "Phone", "properties": {"number": "91XXXXXX22", "provider": "Airtel", "imei": "35XXXX006"}},
    {"id": "Ph-007", "label": "Phone", "properties": {"number": "99XXXXXX11", "provider": "Jio", "imei": "35XXXX007"}},
    {"id": "Ph-008", "label": "Phone", "properties": {"number": "98XXXXXX44", "provider": "Vi", "imei": "35XXXX008"}},
    {"id": "Ph-009", "label": "Phone", "properties": {"number": "97XXXXXX55", "provider": "BSNL", "imei": "35XXXX009"}},
    {"id": "Ph-010", "label": "Phone", "properties": {"number": "90XXXXXX99", "provider": "Jio", "imei": "35XXXX010"}},
    {"id": "Ph-011", "label": "Phone", "properties": {"number": "88XXXXXX77", "provider": "Airtel", "imei": "35XXXX011"}},
    {"id": "Ph-012", "label": "Phone", "properties": {"number": "99XXXXXX66", "provider": "Jio", "imei": "35XXXX012"}},
    {"id": "Ph-013", "label": "Phone", "properties": {"number": "97XXXXXX88", "provider": "Vi", "imei": "35XXXX013"}},
    {"id": "Ph-014", "label": "Phone", "properties": {"number": "96XXXXXX22", "provider": "BSNL", "imei": "35XXXX014"}},
    {"id": "Ph-015", "label": "Phone", "properties": {"number": "95XXXXXX33", "provider": "Airtel", "imei": "35XXXX015"}},
    {"id": "Ph-016", "label": "Phone", "properties": {"number": "BurnerXX01", "provider": "Unknown", "imei": "UNREGISTERED"}},
    {"id": "Ph-017", "label": "Phone", "properties": {"number": "BurnerXX02", "provider": "Unknown", "imei": "UNREGISTERED"}},
    {"id": "Ph-018", "label": "Phone", "properties": {"number": "BurnerXX03", "provider": "Unknown", "imei": "UNREGISTERED"}},

    # ── Vehicles (10) ──
    {"id": "V-001", "label": "Vehicle", "properties": {"registration": "MH-01-AB-1234", "type": "SUV", "make": "Toyota Fortuner"}},
    {"id": "V-002", "label": "Vehicle", "properties": {"registration": "MH-02-CD-5678", "type": "Sedan", "make": "Honda City"}},
    {"id": "V-003", "label": "Vehicle", "properties": {"registration": "MH-04-EF-9012", "type": "Bike", "make": "Pulsar 220"}},
    {"id": "V-004", "label": "Vehicle", "properties": {"registration": "MH-12-GH-3456", "type": "Truck", "make": "Tata 407"}},
    {"id": "V-005", "label": "Vehicle", "properties": {"registration": "MH-43-IJ-7890", "type": "SUV", "make": "Mahindra Scorpio"}},
    {"id": "V-006", "label": "Vehicle", "properties": {"registration": "KA-01-KL-2345", "type": "Sedan", "make": "Hyundai Verna"}},
    {"id": "V-007", "label": "Vehicle", "properties": {"registration": "DL-05-MN-6789", "type": "SUV", "make": "Ford Endeavour"}},
    {"id": "V-008", "label": "Vehicle", "properties": {"registration": "MH-01-OP-1111", "type": "Auto", "make": "Bajaj RE"}},
    {"id": "V-009", "label": "Vehicle", "properties": {"registration": "MH-03-QR-2222", "type": "Bike", "make": "RE Classic 350"}},
    {"id": "V-010", "label": "Vehicle", "properties": {"registration": "MH-46-ST-3333", "type": "Van", "make": "Maruti Eeco"}},

    # ── Locations (12) ──
    {"id": "L-001", "label": "Location", "properties": {"address": "Andheri West, Mumbai", "lat": 19.1364, "lng": 72.8296}},
    {"id": "L-002", "label": "Location", "properties": {"address": "Kurla East, Mumbai", "lat": 19.0728, "lng": 72.8826}},
    {"id": "L-003", "label": "Location", "properties": {"address": "Shivaji Nagar, Pune", "lat": 18.5308, "lng": 73.8475}},
    {"id": "L-004", "label": "Location", "properties": {"address": "Kalyan Railway Stn", "lat": 19.2437, "lng": 73.1355}},
    {"id": "L-005", "label": "Location", "properties": {"address": "Vashi Sector 17, Navi Mumbai", "lat": 19.0771, "lng": 73.0126}},
    {"id": "L-006", "label": "Location", "properties": {"address": "Dadar TT Circle, Mumbai", "lat": 19.0178, "lng": 72.8478}},
    {"id": "L-007", "label": "Location", "properties": {"address": "Bandra Reclamation, Mumbai", "lat": 19.0544, "lng": 72.8256}},
    {"id": "L-008", "label": "Location", "properties": {"address": "Koregaon Park, Pune", "lat": 18.5362, "lng": 73.8936}},
    {"id": "L-009", "label": "Location", "properties": {"address": "Whitefield, Bangalore", "lat": 12.9698, "lng": 77.7500}},
    {"id": "L-010", "label": "Location", "properties": {"address": "Dharavi, Mumbai", "lat": 19.0441, "lng": 72.8557}},
    {"id": "L-011", "label": "Location", "properties": {"address": "CSMT Area, Mumbai", "lat": 18.9398, "lng": 72.8354}},
    {"id": "L-012", "label": "Location", "properties": {"address": "Sitabuldi, Nagpur", "lat": 21.1458, "lng": 79.0882}},

    # ── Cases (5 — matching MOCK_CASES above) ──
    {"id": "C-2023-0891", "label": "Case", "properties": {"fir_number": "FIR/2023/891", "category": "Organized Crime"}},
    {"id": "C-2023-0902", "label": "Case", "properties": {"fir_number": "FIR/2023/902", "category": "Financial Fraud"}},
    {"id": "C-2024-0015", "label": "Case", "properties": {"fir_number": "FIR/2024/015", "category": "Narcotics"}},
    {"id": "C-2024-0042", "label": "Case", "properties": {"fir_number": "FIR/2024/042", "category": "Extortion"}},
    {"id": "C-2024-0078", "label": "Case", "properties": {"fir_number": "FIR/2024/078", "category": "Cyber Crime"}},

    # ── Bank Accounts (8) ──
    {"id": "B-001", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-1234", "bank": "HDFC", "branch": "Andheri"}},
    {"id": "B-002", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-5678", "bank": "SBI", "branch": "Kurla"}},
    {"id": "B-003", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-9012", "bank": "ICICI", "branch": "Pune"}},
    {"id": "B-004", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-3456", "bank": "Axis", "branch": "Thane"}},
    {"id": "B-005", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-7890", "bank": "Kotak", "branch": "Dadar"}},
    {"id": "B-006", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-2222", "bank": "HDFC", "branch": "Bandra"}},
    {"id": "B-007", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-3333", "bank": "PNB", "branch": "Nagpur"}},
    {"id": "B-008", "label": "BankAccount", "properties": {"account_no": "XXXX-XXXX-4444", "bank": "BOB", "branch": "Bangalore"}},

    # ── Organizations (7) ──
    {"id": "O-001", "label": "Organization", "properties": {"name": "ABC Traders Pvt Ltd", "type": "Shell Company", "registered": "Mumbai"}},
    {"id": "O-002", "label": "Organization", "properties": {"name": "XYZ Logistics", "type": "Transport", "registered": "Pune"}},
    {"id": "O-003", "label": "Organization", "properties": {"name": "Star Enterprises", "type": "Real Estate", "registered": "Thane"}},
    {"id": "O-004", "label": "Organization", "properties": {"name": "Delta Finance Co", "type": "NBFC", "registered": "Mumbai"}},
    {"id": "O-005", "label": "Organization", "properties": {"name": "Omega Pharma", "type": "Pharmaceutical", "registered": "Pune"}},
    {"id": "O-006", "label": "Organization", "properties": {"name": "NovaTech Solutions", "type": "IT Services", "registered": "Bangalore"}},
    {"id": "O-007", "label": "Organization", "properties": {"name": "Greenfield Agro", "type": "Agriculture", "registered": "Nagpur"}},
]

# ---------- EDGES ----------

MOCK_EDGES = [
    # ── Person ↔ Phone (USES_PHONE) ──
    {"id": "E001", "source": "P-001", "target": "Ph-001", "type": "USES_PHONE", "properties": {"confidence": 0.95}},
    {"id": "E002", "source": "P-002", "target": "Ph-002", "type": "USES_PHONE", "properties": {"confidence": 0.92}},
    {"id": "E003", "source": "P-003", "target": "Ph-003", "type": "USES_PHONE", "properties": {"confidence": 0.88}},
    {"id": "E004", "source": "P-004", "target": "Ph-004", "type": "USES_PHONE", "properties": {"confidence": 0.90}},
    {"id": "E005", "source": "P-005", "target": "Ph-005", "type": "USES_PHONE", "properties": {"confidence": 0.85}},
    {"id": "E006", "source": "P-006", "target": "Ph-006", "type": "USES_PHONE", "properties": {"confidence": 0.93}},
    {"id": "E007", "source": "P-007", "target": "Ph-007", "type": "USES_PHONE", "properties": {"confidence": 0.91}},
    {"id": "E008", "source": "P-008", "target": "Ph-008", "type": "USES_PHONE", "properties": {"confidence": 0.87}},
    {"id": "E009", "source": "P-009", "target": "Ph-009", "type": "USES_PHONE", "properties": {"confidence": 0.94}},
    {"id": "E010", "source": "P-010", "target": "Ph-010", "type": "USES_PHONE", "properties": {"confidence": 0.89}},
    {"id": "E011", "source": "P-011", "target": "Ph-011", "type": "USES_PHONE", "properties": {"confidence": 0.90}},
    {"id": "E012", "source": "P-012", "target": "Ph-012", "type": "USES_PHONE", "properties": {"confidence": 0.86}},
    {"id": "E013", "source": "P-013", "target": "Ph-013", "type": "USES_PHONE", "properties": {"confidence": 0.92}},
    {"id": "E014", "source": "P-014", "target": "Ph-014", "type": "USES_PHONE", "properties": {"confidence": 0.88}},
    {"id": "E015", "source": "P-015", "target": "Ph-015", "type": "USES_PHONE", "properties": {"confidence": 0.91}},
    # Burner phones used by key suspects
    {"id": "E016", "source": "P-001", "target": "Ph-016", "type": "USES_PHONE", "properties": {"confidence": 0.70}},
    {"id": "E017", "source": "P-005", "target": "Ph-017", "type": "USES_PHONE", "properties": {"confidence": 0.65}},
    {"id": "E018", "source": "P-011", "target": "Ph-018", "type": "USES_PHONE", "properties": {"confidence": 0.60}},

    # ── Phone ↔ Phone (COMMUNICATED_WITH) ──
    {"id": "E019", "source": "Ph-001", "target": "Ph-002", "type": "COMMUNICATED_WITH", "properties": {"confidence": 1.0, "count": 15}},
    {"id": "E020", "source": "Ph-001", "target": "Ph-005", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.95, "count": 8}},
    {"id": "E021", "source": "Ph-002", "target": "Ph-003", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.88, "count": 5}},
    {"id": "E022", "source": "Ph-003", "target": "Ph-008", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.82, "count": 12}},
    {"id": "E023", "source": "Ph-004", "target": "Ph-006", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.90, "count": 7}},
    {"id": "E024", "source": "Ph-005", "target": "Ph-010", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.85, "count": 22}},
    {"id": "E025", "source": "Ph-006", "target": "Ph-012", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.78, "count": 3}},
    {"id": "E026", "source": "Ph-007", "target": "Ph-010", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.92, "count": 9}},
    {"id": "E027", "source": "Ph-009", "target": "Ph-014", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.80, "count": 4}},
    {"id": "E028", "source": "Ph-011", "target": "Ph-012", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.93, "count": 18}},
    {"id": "E029", "source": "Ph-013", "target": "Ph-004", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.87, "count": 6}},
    {"id": "E030", "source": "Ph-015", "target": "Ph-006", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.75, "count": 2}},
    {"id": "E031", "source": "Ph-016", "target": "Ph-017", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.98, "count": 34}},
    {"id": "E032", "source": "Ph-017", "target": "Ph-018", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.95, "count": 21}},
    {"id": "E033", "source": "Ph-016", "target": "Ph-002", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.72, "count": 4}},
    {"id": "E034", "source": "Ph-008", "target": "Ph-014", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.81, "count": 11}},
    {"id": "E035", "source": "Ph-010", "target": "Ph-011", "type": "COMMUNICATED_WITH", "properties": {"confidence": 0.76, "count": 7}},

    # ── Person ↔ Vehicle (OWNS_VEHICLE) ──
    {"id": "E036", "source": "P-001", "target": "V-001", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.90}},
    {"id": "E037", "source": "P-003", "target": "V-002", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.85}},
    {"id": "E038", "source": "P-004", "target": "V-003", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.92}},
    {"id": "E039", "source": "P-005", "target": "V-005", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.88}},
    {"id": "E040", "source": "P-008", "target": "V-004", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.80}},
    {"id": "E041", "source": "P-011", "target": "V-007", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.87}},
    {"id": "E042", "source": "P-015", "target": "V-006", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.91}},
    {"id": "E043", "source": "P-016", "target": "V-009", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.83}},
    {"id": "E044", "source": "P-020", "target": "V-007", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.75}},
    {"id": "E045", "source": "P-022", "target": "V-008", "type": "OWNS_VEHICLE", "properties": {"confidence": 0.78}},

    # ── Vehicle ↔ Location (SEEN_AT) ──
    {"id": "E046", "source": "V-001", "target": "L-001", "type": "SEEN_AT", "properties": {"confidence": 0.82, "timestamp": "2023-10-09T22:15:00"}},
    {"id": "E047", "source": "V-001", "target": "L-006", "type": "SEEN_AT", "properties": {"confidence": 0.79, "timestamp": "2023-10-10T01:30:00"}},
    {"id": "E048", "source": "V-002", "target": "L-003", "type": "SEEN_AT", "properties": {"confidence": 0.85, "timestamp": "2023-11-01T14:45:00"}},
    {"id": "E049", "source": "V-003", "target": "L-004", "type": "SEEN_AT", "properties": {"confidence": 0.71, "timestamp": "2024-01-15T03:00:00"}},
    {"id": "E050", "source": "V-004", "target": "L-003", "type": "SEEN_AT", "properties": {"confidence": 0.88, "timestamp": "2024-01-16T10:20:00"}},
    {"id": "E051", "source": "V-005", "target": "L-002", "type": "SEEN_AT", "properties": {"confidence": 0.90, "timestamp": "2024-02-18T19:00:00"}},
    {"id": "E052", "source": "V-005", "target": "L-010", "type": "SEEN_AT", "properties": {"confidence": 0.77, "timestamp": "2024-02-18T21:30:00"}},
    {"id": "E053", "source": "V-006", "target": "L-009", "type": "SEEN_AT", "properties": {"confidence": 0.83, "timestamp": "2024-03-08T11:00:00"}},
    {"id": "E054", "source": "V-007", "target": "L-011", "type": "SEEN_AT", "properties": {"confidence": 0.86, "timestamp": "2024-01-20T16:45:00"}},
    {"id": "E055", "source": "V-010", "target": "L-004", "type": "SEEN_AT", "properties": {"confidence": 0.74, "timestamp": "2024-01-15T05:00:00"}},
    {"id": "E056", "source": "V-008", "target": "L-002", "type": "SEEN_AT", "properties": {"confidence": 0.80, "timestamp": "2024-02-19T08:30:00"}},
    {"id": "E057", "source": "V-009", "target": "L-007", "type": "SEEN_AT", "properties": {"confidence": 0.68, "timestamp": "2024-01-18T23:15:00"}},

    # ── Person ↔ Case (LINKED_TO_CASE) ──
    {"id": "E058", "source": "P-001", "target": "C-2023-0891", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 1.0}},
    {"id": "E059", "source": "P-002", "target": "C-2023-0891", "type": "LINKED_TO_CASE", "properties": {"role": "Associate", "confidence": 0.85}},
    {"id": "E060", "source": "P-005", "target": "C-2023-0891", "type": "LINKED_TO_CASE", "properties": {"role": "Associate", "confidence": 0.78}},
    {"id": "E061", "source": "P-002", "target": "C-2023-0902", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.92}},
    {"id": "E062", "source": "P-003", "target": "C-2023-0902", "type": "LINKED_TO_CASE", "properties": {"role": "Beneficiary", "confidence": 0.88}},
    {"id": "E063", "source": "P-008", "target": "C-2023-0902", "type": "LINKED_TO_CASE", "properties": {"role": "Witness", "confidence": 0.70}},
    {"id": "E064", "source": "P-005", "target": "C-2024-0015", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.95}},
    {"id": "E065", "source": "P-010", "target": "C-2024-0015", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.90}},
    {"id": "E066", "source": "P-012", "target": "C-2024-0015", "type": "LINKED_TO_CASE", "properties": {"role": "Courier", "confidence": 0.82}},
    {"id": "E067", "source": "P-006", "target": "C-2024-0015", "type": "LINKED_TO_CASE", "properties": {"role": "Associate", "confidence": 0.75}},
    {"id": "E068", "source": "P-004", "target": "C-2024-0042", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.93}},
    {"id": "E069", "source": "P-013", "target": "C-2024-0042", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.88}},
    {"id": "E070", "source": "P-022", "target": "C-2024-0042", "type": "LINKED_TO_CASE", "properties": {"role": "Victim", "confidence": 1.0}},
    {"id": "E071", "source": "P-015", "target": "C-2024-0078", "type": "LINKED_TO_CASE", "properties": {"role": "Suspect", "confidence": 0.90}},
    {"id": "E072", "source": "P-011", "target": "C-2024-0078", "type": "LINKED_TO_CASE", "properties": {"role": "Handler", "confidence": 0.80}},

    # ── Person ↔ BankAccount (ASSOCIATED_WITH) ──
    {"id": "E073", "source": "P-001", "target": "B-001", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.92}},
    {"id": "E074", "source": "P-002", "target": "B-002", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.88}},
    {"id": "E075", "source": "P-003", "target": "B-003", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.85}},
    {"id": "E076", "source": "P-004", "target": "B-004", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.90}},
    {"id": "E077", "source": "P-005", "target": "B-005", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.87}},
    {"id": "E078", "source": "P-007", "target": "B-006", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.82}},
    {"id": "E079", "source": "P-009", "target": "B-007", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.79}},
    {"id": "E080", "source": "P-015", "target": "B-008", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.86}},
    # Cross-person accounts (suspicious)
    {"id": "E081", "source": "P-010", "target": "B-001", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.65}},
    {"id": "E082", "source": "P-012", "target": "B-005", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.60}},
    {"id": "E083", "source": "P-011", "target": "B-008", "type": "ASSOCIATED_WITH", "properties": {"confidence": 0.55}},

    # ── BankAccount ↔ BankAccount (TRANSFERRED_TO) ──
    {"id": "E084", "source": "B-001", "target": "B-002", "type": "TRANSFERRED_TO", "properties": {"amount": 250000, "date": "2023-10-08"}},
    {"id": "E085", "source": "B-002", "target": "B-003", "type": "TRANSFERRED_TO", "properties": {"amount": 180000, "date": "2023-10-09"}},
    {"id": "E086", "source": "B-003", "target": "B-005", "type": "TRANSFERRED_TO", "properties": {"amount": 500000, "date": "2023-11-02"}},
    {"id": "E087", "source": "B-004", "target": "B-001", "type": "TRANSFERRED_TO", "properties": {"amount": 120000, "date": "2024-02-15"}},
    {"id": "E088", "source": "B-005", "target": "B-006", "type": "TRANSFERRED_TO", "properties": {"amount": 75000, "date": "2024-01-20"}},
    {"id": "E089", "source": "B-006", "target": "B-008", "type": "TRANSFERRED_TO", "properties": {"amount": 320000, "date": "2024-03-05"}},
    {"id": "E090", "source": "B-007", "target": "B-004", "type": "TRANSFERRED_TO", "properties": {"amount": 95000, "date": "2024-02-10"}},

    # ── Person ↔ Organization (WORKS_FOR / DIRECTOR_OF) ──
    {"id": "E091", "source": "P-001", "target": "O-001", "type": "DIRECTOR_OF", "properties": {"confidence": 0.95}},
    {"id": "E092", "source": "P-003", "target": "O-002", "type": "WORKS_FOR", "properties": {"confidence": 0.88}},
    {"id": "E093", "source": "P-005", "target": "O-003", "type": "DIRECTOR_OF", "properties": {"confidence": 0.82}},
    {"id": "E094", "source": "P-008", "target": "O-002", "type": "WORKS_FOR", "properties": {"confidence": 0.85}},
    {"id": "E095", "source": "P-011", "target": "O-004", "type": "DIRECTOR_OF", "properties": {"confidence": 0.90}},
    {"id": "E096", "source": "P-015", "target": "O-006", "type": "WORKS_FOR", "properties": {"confidence": 0.91}},
    {"id": "E097", "source": "P-009", "target": "O-007", "type": "WORKS_FOR", "properties": {"confidence": 0.87}},
    {"id": "E098", "source": "P-016", "target": "O-001", "type": "WORKS_FOR", "properties": {"confidence": 0.72}},
    {"id": "E099", "source": "P-017", "target": "O-003", "type": "WORKS_FOR", "properties": {"confidence": 0.68}},
    {"id": "E100", "source": "P-018", "target": "O-005", "type": "WORKS_FOR", "properties": {"confidence": 0.80}},
    {"id": "E101", "source": "P-019", "target": "O-005", "type": "DIRECTOR_OF", "properties": {"confidence": 0.93}},
    {"id": "E102", "source": "P-020", "target": "O-004", "type": "WORKS_FOR", "properties": {"confidence": 0.76}},

    # ── Organization ↔ BankAccount (HOLDS_ACCOUNT) ──
    {"id": "E103", "source": "O-001", "target": "B-001", "type": "HOLDS_ACCOUNT", "properties": {"confidence": 0.90}},
    {"id": "E104", "source": "O-002", "target": "B-003", "type": "HOLDS_ACCOUNT", "properties": {"confidence": 0.85}},
    {"id": "E105", "source": "O-003", "target": "B-004", "type": "HOLDS_ACCOUNT", "properties": {"confidence": 0.88}},
    {"id": "E106", "source": "O-004", "target": "B-006", "type": "HOLDS_ACCOUNT", "properties": {"confidence": 0.82}},
    {"id": "E107", "source": "O-006", "target": "B-008", "type": "HOLDS_ACCOUNT", "properties": {"confidence": 0.87}},

    # ── Person ↔ Location (RESIDES_AT / VISITED) ──
    {"id": "E108", "source": "P-001", "target": "L-001", "type": "RESIDES_AT", "properties": {"confidence": 0.95}},
    {"id": "E109", "source": "P-002", "target": "L-002", "type": "RESIDES_AT", "properties": {"confidence": 0.90}},
    {"id": "E110", "source": "P-003", "target": "L-003", "type": "RESIDES_AT", "properties": {"confidence": 0.88}},
    {"id": "E111", "source": "P-004", "target": "L-004", "type": "RESIDES_AT", "properties": {"confidence": 0.92}},
    {"id": "E112", "source": "P-005", "target": "L-010", "type": "RESIDES_AT", "properties": {"confidence": 0.85}},
    {"id": "E113", "source": "P-006", "target": "L-005", "type": "RESIDES_AT", "properties": {"confidence": 0.90}},
    {"id": "E114", "source": "P-010", "target": "L-007", "type": "RESIDES_AT", "properties": {"confidence": 0.87}},
    {"id": "E115", "source": "P-015", "target": "L-009", "type": "RESIDES_AT", "properties": {"confidence": 0.91}},
    {"id": "E116", "source": "P-009", "target": "L-012", "type": "RESIDES_AT", "properties": {"confidence": 0.86}},
    {"id": "E117", "source": "P-001", "target": "L-006", "type": "VISITED", "properties": {"confidence": 0.72, "timestamp": "2023-10-10T01:00:00"}},
    {"id": "E118", "source": "P-005", "target": "L-002", "type": "VISITED", "properties": {"confidence": 0.68, "timestamp": "2024-02-18T18:30:00"}},
    {"id": "E119", "source": "P-011", "target": "L-011", "type": "VISITED", "properties": {"confidence": 0.75, "timestamp": "2024-01-20T16:00:00"}},

    # ── Person ↔ Person (KNOWN_ASSOCIATE) ──
    {"id": "E120", "source": "P-001", "target": "P-002", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.92}},
    {"id": "E121", "source": "P-001", "target": "P-005", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.85}},
    {"id": "E122", "source": "P-004", "target": "P-013", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.88}},
    {"id": "E123", "source": "P-005", "target": "P-010", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.80}},
    {"id": "E124", "source": "P-011", "target": "P-020", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.78}},
    {"id": "E125", "source": "P-003", "target": "P-008", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.90}},
    {"id": "E126", "source": "P-006", "target": "P-012", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.82}},
    {"id": "E127", "source": "P-016", "target": "P-021", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.75}},
    {"id": "E128", "source": "P-018", "target": "P-019", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.83}},
    {"id": "E129", "source": "P-023", "target": "P-024", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.70}},
    {"id": "E130", "source": "P-021", "target": "P-025", "type": "KNOWN_ASSOCIATE", "properties": {"confidence": 0.77}},

    # ── Organization ↔ Location (REGISTERED_AT) ──
    {"id": "E131", "source": "O-001", "target": "L-001", "type": "REGISTERED_AT", "properties": {"confidence": 0.95}},
    {"id": "E132", "source": "O-002", "target": "L-003", "type": "REGISTERED_AT", "properties": {"confidence": 0.90}},
    {"id": "E133", "source": "O-003", "target": "L-004", "type": "REGISTERED_AT", "properties": {"confidence": 0.88}},
    {"id": "E134", "source": "O-005", "target": "L-008", "type": "REGISTERED_AT", "properties": {"confidence": 0.85}},
    {"id": "E135", "source": "O-006", "target": "L-009", "type": "REGISTERED_AT", "properties": {"confidence": 0.92}},
    {"id": "E136", "source": "O-007", "target": "L-012", "type": "REGISTERED_AT", "properties": {"confidence": 0.87}},
]


MOCK_LEADS = [
    {
        "id": "L-101",
        "title": "Shared Communication Before Incident",
        "priority": "High",
        "related_cases": ["C-2023-0891", "C-2023-0902"],
        "related_entities": ["P-001", "P-002", "Ph-001", "Ph-002"],
        "explanation": "P-001 and P-002 communicated 15 times prior to the incidents recorded in their respective cases. Burner phone Ph-016 also linked to both suspects.",
        "confidence": 0.92,
        "created_by": "System",
        "created_date": (datetime.now() - timedelta(days=1)).isoformat(),
        "status": "Unreviewed",
        "review_note": ""
    },
    {
        "id": "L-102",
        "title": "Cross-Case Financial Trail",
        "priority": "High",
        "related_cases": ["C-2023-0891", "C-2024-0015"],
        "related_entities": ["P-001", "P-005", "B-001", "B-005", "O-001"],
        "explanation": "Money transferred from B-001 (linked to P-001 and ABC Traders) through B-002 to B-005 (linked to P-005). Both suspects are connected to different cases.",
        "confidence": 0.88,
        "created_by": "System",
        "created_date": (datetime.now() - timedelta(days=3)).isoformat(),
        "status": "Unreviewed",
        "review_note": ""
    },
    {
        "id": "L-103",
        "title": "Narcotics Network Hub Identified",
        "priority": "Critical",
        "related_cases": ["C-2024-0015"],
        "related_entities": ["P-005", "P-010", "P-012", "Ph-017", "L-010"],
        "explanation": "P-005 acts as a central hub connecting to P-010 and P-012 via phone communications and shared location visits in Dharavi. Burner phone Ph-017 shows 34 calls to another burner.",
        "confidence": 0.95,
        "created_by": "System",
        "created_date": (datetime.now() - timedelta(hours=6)).isoformat(),
        "status": "Unreviewed",
        "review_note": ""
    },
]

MOCK_TIMELINE = [
    {"id": "T1", "date": "2023-10-05T10:00:00Z", "type": "COMMUNICATION", "description": "Call between Ph-001 and Ph-002 (15 calls cluster)", "entities": ["Ph-001", "Ph-002", "P-001", "P-002"]},
    {"id": "T2", "date": "2023-10-08T14:00:00Z", "type": "FINANCIAL", "description": "₹2,50,000 transferred from B-001 to B-002", "entities": ["B-001", "B-002", "P-001", "P-002"]},
    {"id": "T3", "date": "2023-10-09T22:15:00Z", "type": "SURVEILLANCE", "description": "V-001 (MH-01-AB-1234) spotted at Andheri West", "entities": ["V-001", "L-001", "P-001"]},
    {"id": "T4", "date": "2023-10-10T01:30:00Z", "type": "SURVEILLANCE", "description": "V-001 spotted at Dadar TT Circle", "entities": ["V-001", "L-006"]},
    {"id": "T5", "date": "2023-10-10T14:30:00Z", "type": "INCIDENT", "description": "Incident reported for C-2023-0891", "entities": ["C-2023-0891", "P-001", "V-001"]},
    {"id": "T6", "date": "2023-11-01T09:15:00Z", "type": "INCIDENT", "description": "Financial fraud incident reported for C-2023-0902", "entities": ["C-2023-0902", "P-002", "P-003"]},
    {"id": "T7", "date": "2023-11-02T11:00:00Z", "type": "FINANCIAL", "description": "₹5,00,000 transferred from B-003 to B-005 (suspicious layering)", "entities": ["B-003", "B-005", "P-003", "P-005"]},
    {"id": "T8", "date": "2024-01-15T03:00:00Z", "type": "SURVEILLANCE", "description": "V-003 and V-010 spotted at Kalyan Railway Station (late night)", "entities": ["V-003", "V-010", "L-004", "P-004"]},
    {"id": "T9", "date": "2024-01-18T23:15:00Z", "type": "INCIDENT", "description": "Narcotics case C-2024-0015 initiated after raid", "entities": ["C-2024-0015", "P-005", "P-010", "L-010"]},
    {"id": "T10", "date": "2024-02-18T19:00:00Z", "type": "INCIDENT", "description": "Extortion complaint filed — C-2024-0042", "entities": ["C-2024-0042", "P-004", "P-013", "P-022"]},
    {"id": "T11", "date": "2024-03-08T11:00:00Z", "type": "INCIDENT", "description": "Cyber crime case C-2024-0078 registered from Bangalore", "entities": ["C-2024-0078", "P-015", "P-011", "L-009"]},
]

MOCK_STATS = {
    "total_cases": 1542,
    "total_entities": 8432,
    "total_nodes": len(MOCK_NODES),
    "total_edges": len(MOCK_EDGES),
    "imported_records": 105432,
    "data_quality_warnings": 23,
    "active_users": 15,
    "entity_breakdown": {
        "Person": sum(1 for n in MOCK_NODES if n["label"] == "Person"),
        "Phone": sum(1 for n in MOCK_NODES if n["label"] == "Phone"),
        "Vehicle": sum(1 for n in MOCK_NODES if n["label"] == "Vehicle"),
        "Location": sum(1 for n in MOCK_NODES if n["label"] == "Location"),
        "Case": sum(1 for n in MOCK_NODES if n["label"] == "Case"),
        "BankAccount": sum(1 for n in MOCK_NODES if n["label"] == "BankAccount"),
        "Organization": sum(1 for n in MOCK_NODES if n["label"] == "Organization"),
    },
    "top_connectors": [
        {"id": "P-001", "name": "Arjun Kumar", "connections": 12},
        {"id": "P-005", "name": "Mohammed Shaikh", "connections": 10},
        {"id": "P-011", "name": "Sanjay Gupta", "connections": 8},
        {"id": "P-002", "name": "Vikram Singh", "connections": 7},
        {"id": "P-003", "name": "Rajesh Patil", "connections": 7},
    ],
}
